// Original typing adventures for kids. Each adventure is a themed
// story battle: type the line to "attack" / advance the story.
// All story text and typing lines are authored here from scratch.

export const ADVENTURES = [
  {
    id: "adv-monster",
    title: "Monster Mash Forest",
    emoji: "👾",
    bg: "img/adv-monster-forest.jpg",
    accent: "#a06bff",
    goalLabel: "Giant Grumble Monster",
    intro: "Deep in the Glow Forest, a big sleepy monster blocks the path. Type the magic words to turn its grumpy face into a happy one!",
    winText: "The monster giggles and lets you pass. New friend unlocked!",
    stages: [
      { say: "Wake the magic with a spark.",        type: "the glow forest is alive" },
      { say: "Zap the monster's left paw!",         type: "a fuzzy paw waves hello" },
      { say: "Now the right paw!",                  type: "the monster blinks its big eyes" },
      { say: "Tickle its tummy with words!",        type: "purple mushrooms light the trail" },
      { say: "Almost there, keep typing!",          type: "the grumpy frown starts to fade" },
      { say: "Final magic blast!",                  type: "the giant monster laughs out loud" },
    ],
  },
  {
    id: "adv-alien",
    title: "Galaxy Defenders",
    emoji: "🛸",
    bg: "img/adv-alien-space.jpg",
    accent: "#37b6ff",
    goalLabel: "Sneaky Space Aliens",
    intro: "Silly aliens are zooming around your ship! Type fast to power your laser and bop them gently back to their planet.",
    winText: "All aliens bounced home safely. The galaxy is calm again!",
    stages: [
      { say: "Charge the laser cannon!",            type: "the ship hums and the lights blink" },
      { say: "Fire at the green alien!",            type: "a green alien spins past a star" },
      { say: "Reload and aim again!",               type: "we zoom between the bright planets" },
      { say: "Bop the purple alien!",               type: "the purple alien wiggles its arms" },
      { say: "Dodge the asteroid, then shoot!",     type: "rocks tumble through the dark sky" },
      { say: "Last alien, blast off!",              type: "the brave crew saves the whole galaxy" },
    ],
  },
  {
    id: "adv-bull",
    title: "The Great Bull Tug",
    emoji: "🐂",
    bg: "img/adv-bull-ranch.jpg",
    accent: "#e0a23c",
    goalLabel: "Big Strong Bull",
    intro: "It's the farm tug-of-war! Grab the rope and type each pull to drag the giant friendly bull across the line.",
    winText: "You win the tug-of-war! The bull moos and shares his hay.",
    stages: [
      { say: "Grip the rope tight!",                type: "hold the rope and dig your boots in" },
      { say: "Heave! Pull hard!",                   type: "pull the rope across the green field" },
      { say: "The bull pulls back, hold on!",       type: "the big bull snorts and grins wide" },
      { say: "Use your legs, pull again!",          type: "dust flies up around our muddy boots" },
      { say: "He is sliding, keep pulling!",        type: "we win this game one tug at a time" },
      { say: "One last mighty heave!",              type: "the strong bull slides across the line" },
    ],
  },
  {
    id: "adv-dragon",
    title: "Dragon's Treasure",
    emoji: "🐲",
    bg: "img/adv-dragon-castle.jpg",
    accent: "#ff7a45",
    goalLabel: "Friendly Castle Dragon",
    intro: "A kind dragon guards a castle of gold. Answer its riddles by typing them out, and it will share the treasure!",
    winText: "The dragon smiles and opens the treasure chest just for you!",
    stages: [
      { say: "Greet the dragon politely.",          type: "hello mister dragon may we come in" },
      { say: "Climb the castle steps.",             type: "we climb the steep stone steps slowly" },
      { say: "Light the golden torches.",           type: "warm torches glow along the hallway" },
      { say: "Solve the shiny riddle.",             type: "what shines like the sun but is gold" },
      { say: "Open the treasure chest!",            type: "the heavy lid creaks open with a pop" },
      { say: "Thank the dragon!",                   type: "the dragon shares its sparkling gems" },
    ],
  },
  {
    id: "adv-pirate",
    title: "Treasure Island Voyage",
    emoji: "🏴‍☠️",
    bg: "img/adv-pirate-sea.jpg",
    accent: "#1fb6a8",
    goalLabel: "Hidden Pirate Treasure",
    intro: "Ahoy! Sail your ship to the island marked with a big X. Type each command to steer toward the buried gold.",
    winText: "X marks the spot! You dig up the chest of golden coins!",
    stages: [
      { say: "Raise the sails!",                    type: "raise the sails and catch the wind" },
      { say: "Steer toward the island.",            type: "turn the wheel toward the green island" },
      { say: "Watch for the friendly parrot.",      type: "a red parrot flies above the blue waves" },
      { say: "Drop the anchor near shore.",         type: "we splash down the heavy iron anchor" },
      { say: "Follow the map to the X.",            type: "walk ten steps past the tall palm tree" },
      { say: "Dig up the treasure!",                type: "we dig and find a chest of shiny gold" },
    ],
  },
  {
    id: "adv-dino",
    title: "Dino Valley Dash",
    emoji: "🦕",
    bg: "img/adv-dino-jungle.jpg",
    accent: "#46c267",
    goalLabel: "Rumbling Volcano",
    intro: "The volcano is rumbling! Help your dino friends dash to safety by typing each step of the escape across the jungle.",
    winText: "Everyone made it to safety! The dinos cheer and stomp happily.",
    stages: [
      { say: "Wake the sleepy dinos!",              type: "the green dino opens its big eyes" },
      { say: "Run past the waterfall!",             type: "we dash beside the cool splashing falls" },
      { say: "Hop over the river rocks!",           type: "jump from rock to rock across the river" },
      { say: "Help the little dino keep up!",       type: "the tiny dino runs as fast as it can" },
      { say: "Climb the safe green hill!",          type: "we climb the hill far from the hot lava" },
      { say: "Everyone is safe, cheer!",            type: "the happy dinos stomp and roar with joy" },
    ],
  },
  {
    id: "adv-ocean",
    title: "Ocean Rescue Dive",
    emoji: "🦈",
    bg: "img/adv-ocean-shark.jpg",
    accent: "#22b8e6",
    goalLabel: "Big Friendly Shark",
    intro: "A gentle shark has a fish hook stuck in its fin! Dive down and type carefully to help free your new ocean friend.",
    winText: "The shark is free and does a happy flip! The whole reef cheers.",
    stages: [
      { say: "Put on your diving mask!",            type: "we slip on the mask and dive down deep" },
      { say: "Swim past the coral reef!",           type: "bright fish dart around the pink coral" },
      { say: "Say hello to the shark!",             type: "the big shark gives a gentle smile" },
      { say: "Carefully reach the fin!",            type: "we float close and reach out a hand" },
      { say: "Gently pull the hook free!",          type: "the little hook slides out with care" },
      { say: "Celebrate the rescue!",               type: "the happy shark spins in a big loop" },
    ],
  },
  {
    id: "adv-ninja",
    title: "Ninja Dojo Trials",
    emoji: "🥷",
    bg: "img/adv-ninja-dojo.jpg",
    accent: "#ef4d4d",
    goalLabel: "Master's Challenge",
    intro: "Train at the moonlit dojo to earn your typing belt! Type each move quickly and quietly like a true ninja.",
    winText: "You earn your golden belt! The master gives a proud bow.",
    stages: [
      { say: "Bow to begin the trial.",             type: "the young ninja bows with great respect" },
      { say: "Practice the silent step!",           type: "step softly across the wooden floor" },
      { say: "Strike the training dummy!",          type: "a quick chop hits the wooden post" },
      { say: "Catch the falling petals!",           type: "pink petals drift down in the moonlight" },
      { say: "Dodge and spin away!",                type: "the ninja rolls and springs back up" },
      { say: "Earn your belt!",                     type: "the master smiles and bows to you" },
    ],
  },
  {
    id: "adv-race",
    title: "Speed Racer Cup",
    emoji: "🏎️",
    bg: "img/adv-race-track.jpg",
    accent: "#ff5a4d",
    goalLabel: "Checkered Finish Line",
    intro: "Start your engines! Type each lap as fast as you can to race your cartoon car to the finish line and win the cup.",
    winText: "You cross the finish line first! The crowd cheers your name!",
    stages: [
      { say: "Rev up the engine!",                  type: "the little red car revs up to go" },
      { say: "Zoom around the first turn!",         type: "we speed around the sharp left turn" },
      { say: "Pass the blue car!",                  type: "we zip right past the slow blue car" },
      { say: "Dodge the spinning tires!",           type: "swerve around the bouncing rubber tires" },
      { say: "Take the final lap!",                 type: "the last lap is fast and very loud" },
      { say: "Grab the checkered flag!",            type: "we win the race and lift the gold cup" },
    ],
  },
  {
    id: "adv-robot",
    title: "Robot Factory Fix",
    emoji: "🤖",
    bg: "img/adv-robot-factory.jpg",
    accent: "#9b6bff",
    goalLabel: "Jammed Mega Robot",
    intro: "The big factory robot is stuck and beeping! Type the repair codes to get all the cheerful robots working again.",
    winText: "Beep boop! The robots whirr back to life and dance together!",
    stages: [
      { say: "Power up the control panel!",         type: "the buttons blink red and then green" },
      { say: "Tighten the loose bolt!",             type: "we turn the bolt with a shiny wrench" },
      { say: "Oil the squeaky gears!",              type: "the gears spin smoothly once again" },
      { say: "Restart the conveyor belt!",          type: "the belt rolls and the robots wave" },
      { say: "Fix the wobbly arm!",                 type: "the robot arm swings up and down" },
      { say: "Bring the mega robot online!",        type: "the big robot beeps and does a dance" },
    ],
  },
  {
    id: "adv-ghost",
    title: "Friendly Ghost Manor",
    emoji: "👻",
    bg: "img/adv-ghost-house.jpg",
    accent: "#7ee08a",
    goalLabel: "Shy Little Ghosts",
    intro: "The ghosts in the manor are just lonely, not scary! Type kind words to make them giggle and light up the spooky house.",
    winText: "The ghosts glow with joy and throw you a friendly party!",
    stages: [
      { say: "Knock on the creaky door.",           type: "the old wooden door swings open wide" },
      { say: "Wave to the floating ghost!",         type: "a smiling ghost waves a fluffy hand" },
      { say: "Light the friendly pumpkins!",        type: "the orange pumpkins glow warm and bright" },
      { say: "Say hi to the silly bat!",            type: "the little bat flaps with happy eyes" },
      { say: "Tell a funny joke!",                  type: "the ghosts giggle and float in circles" },
      { say: "Join the ghost party!",               type: "we dance with our new glowing friends" },
    ],
  },
  {
    id: "adv-yeti",
    title: "Snowy Yeti Peak",
    emoji: "⛄",
    bg: "img/adv-yeti-peak.jpg",
    accent: "#5fb6ff",
    goalLabel: "Lonely Mountain Yeti",
    intro: "A big fluffy yeti waves from the snowy peak, hoping for a friend! Climb the mountain by typing each frosty step.",
    winText: "The yeti gives you a giant fuzzy hug! Best snow day ever!",
    stages: [
      { say: "Bundle up in your warm coat!",        type: "we zip the coat and pull on mittens" },
      { say: "Trek through the deep snow!",         type: "our boots crunch in the soft white snow" },
      { say: "Wave to the friendly yeti!",          type: "the big yeti waves a fuzzy white paw" },
      { say: "Build a tiny snowman!",               type: "we roll three snowballs into a stack" },
      { say: "Climb the icy ledge!",                type: "we climb the slippery ledge with care" },
      { say: "Hug your new yeti friend!",           type: "the happy yeti gives a giant warm hug" },
    ],
  },
];
