// Original typing adventures for kids. Each adventure is a themed
// story battle: type the line to "attack" / advance the story.
// All story text and typing lines are authored here from scratch.

export const ADVENTURES = [
  {
    id: "adv-monster",
    title: "Monster Mash Forest",
    emoji: "👾",
    bg: "img/adv-monster-forest.jpg",
    accent: "#a06bff",
    goalLabel: "Giant Grumble Monster",
    intro: "Deep in the Glow Forest, a big sleepy monster blocks the path. Type the magic words to turn its grumpy face into a happy one!",
    winText: "The monster giggles and lets you pass. New friend unlocked!",
    stages: [
      { say: "Wake the magic with a spark.",        type: "the glow forest is alive" },
      { say: "Zap the monster's left paw!",         type: "a fuzzy paw waves hello" },
      { say: "Now the right paw!",                  type: "the monster blinks its big eyes" },
      { say: "Tickle its tummy with words!",        type: "purple mushrooms light the trail" },
      { say: "Almost there, keep typing!",          type: "the grumpy frown starts to fade" },
      { say: "Final magic blast!",                  type: "the giant monster laughs out loud" },
    ],
  },
  {
    id: "adv-alien",
    title: "Galaxy Defenders",
    emoji: "🛸",
    bg: "img/adv-alien-space.jpg",
    accent: "#37b6ff",
    goalLabel: "Sneaky Space Aliens",
    intro: "Silly aliens are zooming around your ship! Type fast to power your laser and bop them gently back to their planet.",
    winText: "All aliens bounced home safely. The galaxy is calm again!",
    stages: [
      { say: "Charge the laser cannon!",            type: "the ship hums and the lights blink" },
      { say: "Fire at the green alien!",            type: "a green alien spins past a star" },
      { say: "Reload and aim again!",               type: "we zoom between the bright planets" },
      { say: "Bop the purple alien!",               type: "the purple alien wiggles its arms" },
      { say: "Dodge the asteroid, then shoot!",     type: "rocks tumble through the dark sky" },
      { say: "Last alien, blast off!",              type: "the brave crew saves the whole galaxy" },
    ],
  },
  {
    id: "adv-bull",
    title: "The Great Bull Tug",
    emoji: "🐂",
    bg: "img/adv-bull-ranch.jpg",
    accent: "#e0a23c",
    goalLabel: "Big Strong Bull",
    intro: "It's the farm tug-of-war! Grab the rope and type each pull to drag the giant friendly bull across the line.",
    winText: "You win the tug-of-war! The bull moos and shares his hay.",
    stages: [
      { say: "Grip the rope tight!",                type: "hold the rope and dig your boots in" },
      { say: "Heave! Pull hard!",                   type: "pull the rope across the green field" },
      { say: "The bull pulls back, hold on!",       type: "the big bull snorts and grins wide" },
      { say: "Use your legs, pull again!",          type: "dust flies up around our muddy boots" },
      { say: "He is sliding, keep pulling!",        type: "we win this game one tug at a time" },
      { say: "One last mighty heave!",              type: "the strong bull slides across the line" },
    ],
  },
  {
    id: "adv-dragon",
    title: "Dragon's Treasure",
    emoji: "🐲",
    bg: "img/adv-dragon-castle.jpg",
    accent: "#ff7a45",
    goalLabel: "Friendly Castle Dragon",
    intro: "A kind dragon guards a castle of gold. Answer its riddles by typing them out, and it will share the treasure!",
    winText: "The dragon smiles and opens the treasure chest just for you!",
    stages: [
      { say: "Greet the dragon politely.",          type: "hello mister dragon may we come in" },
      { say: "Climb the castle steps.",             type: "we climb the steep stone steps slowly" },
      { say: "Light the golden torches.",           type: "warm torches glow along the hallway" },
      { say: "Solve the shiny riddle.",             type: "what shines like the sun but is gold" },
      { say: "Open the treasure chest!",            type: "the heavy lid creaks open with a pop" },
      { say: "Thank the dragon!",                   type: "the dragon shares its sparkling gems" },
    ],
  },
  {
    id: "adv-pirate",
    title: "Treasure Island Voyage",
    emoji: "🏴‍☠️",
    bg: "img/adv-pirate-sea.jpg",
    accent: "#1fb6a8",
    goalLabel: "Hidden Pirate Treasure",
    intro: "Ahoy! Sail your ship to the island marked with a big X. Type each command to steer toward the buried gold.",
    winText: "X marks the spot! You dig up the chest of golden coins!",
    stages: [
      { say: "Raise the sails!",                    type: "raise the sails and catch the wind" },
      { say: "Steer toward the island.",            type: "turn the wheel toward the green island" },
      { say: "Watch for the friendly parrot.",      type: "a red parrot flies above the blue waves" },
      { say: "Drop the anchor near shore.",         type: "we splash down the heavy iron anchor" },
      { say: "Follow the map to the X.",            type: "walk ten steps past the tall palm tree" },
      { say: "Dig up the treasure!",                type: "we dig and find a chest of shiny gold" },
    ],
  },
  {
    id: "adv-dino",
    title: "Dino Valley Dash",
    emoji: "🦕",
    bg: "img/adv-dino-jungle.jpg",
    accent: "#46c267",
    goalLabel: "Rumbling Volcano",
    intro: "The volcano is rumbling! Help your dino friends dash to safety by typing each step of the escape across the jungle.",
    winText: "Everyone made it to safety! The dinos cheer and stomp happily.",
    stages: [
      { say: "Wake the sleepy dinos!",              type: "the green dino opens its big eyes" },
      { say: "Run past the waterfall!",             type: "we dash beside the cool splashing falls" },
      { say: "Hop over the river rocks!",           type: "jump from rock to rock across the river" },
      { say: "Help the little dino keep up!",       type: "the tiny dino runs as fast as it can" },
      { say: "Climb the safe green hill!",          type: "we climb the hill far from the hot lava" },
      { say: "Everyone is safe, cheer!",            type: "the happy dinos stomp and roar with joy" },
    ],
  },
];
