// Original typing adventures for kids. Each quest is a long, connected
// story: every "type" line is one sentence of the tale, so completing a
// quest reads like a real short story while practising typing.
// All story text and typing lines are authored here from scratch.

export const ADVENTURES = [
  {
    id: "adv-monster",
    title: "Monster Mash Forest",
    emoji: "👾",
    bg: "img/adv-monster-forest.jpg",
    accent: "#a06bff",
    goalLabel: "Giant Grumble Monster",
    intro: "Deep in the Glow Forest, a big lonely monster blocks the path. Type the story to turn its grumpy frown into a happy smile and make a new friend!",
    winText: "The monster giggles and hugs you. You found a forest friend forever!",
    stages: [
      { say: "Enter the glowing woods...", type: "deep in the glow forest the trees shine with soft blue light" },
      { say: "Something blocks the path!", type: "a giant fuzzy monster sits right in the middle of the trail" },
      { say: "It seems so sad.", type: "it looks very grumpy and lets out a long and lonely sigh" },
      { say: "Be brave and kind.", type: "you step a little closer and smile up at the big monster" },
      { say: "It notices you.", type: "the monster blinks its one huge eye and tilts its furry head" },
      { say: "Offer a gift.", type: "you say hello and hold out a sweet glowing berry to share" },
      { say: "It takes a taste.", type: "the monster sniffs the berry and gives it one tiny careful bite" },
      { say: "Here comes a smile!", type: "a big happy grin slowly spreads across its soft furry face" },
      { say: "The forest wakes up.", type: "the whole forest glows brighter as the monster begins to laugh" },
      { say: "Dance together!", type: "you and the monster dance in circles under the shining trees" },
      { say: "A friend for the journey.", type: "now you have a brand new friend to guide you through the woods" },
    ],
  },
  {
    id: "adv-alien",
    title: "Galaxy Defenders",
    emoji: "🛸",
    bg: "img/adv-alien-space.jpg",
    accent: "#37b6ff",
    goalLabel: "Sneaky Space Aliens",
    intro: "Silly aliens are zooming around your ship! They only want to play. Type the story to bounce them gently home and keep the galaxy giggling.",
    winText: "Every alien floated home happy. The whole galaxy sparkles with joy!",
    stages: [
      { say: "High above the world...", type: "your little spaceship floats high above the bright blue earth" },
      { say: "Visitors arrive!", type: "tiny silly aliens zoom around and giggle near the round windows" },
      { say: "They are friendly.", type: "they are not mean at all they just want a friend to play with" },
      { say: "Say hello!", type: "you wave at them happily through the thick glass window" },
      { say: "A green one spins by.", type: "a green alien twirls past and waves all four of its arms" },
      { say: "Start the fun game.", type: "you gently press a glowing button to begin a bouncy game" },
      { say: "Bubbles everywhere!", type: "soft round bubbles float out and bounce the aliens around" },
      { say: "They love it!", type: "the aliens laugh and chase the bubbles all across the stars" },
      { say: "Time to go home.", type: "one by one they drift back toward their colorful little planet" },
      { say: "A sweet goodbye.", type: "they blow you a happy goodbye kiss from very far away" },
      { say: "Peace in the stars.", type: "the galaxy is calm again and the bright stars softly twinkle" },
    ],
  },
  {
    id: "adv-bull",
    title: "The Great Bull Tug",
    emoji: "🐂",
    bg: "img/adv-bull-ranch.jpg",
    accent: "#e0a23c",
    goalLabel: "Big Strong Bull",
    intro: "It is farm game day! A big friendly bull wants a tug-of-war. Type the story to pull with all your might and win the playful match.",
    winText: "You win the tug-of-war! The bull moos and shares a big pile of hay.",
    stages: [
      { say: "A sunny farm day.", type: "the sun is warm and the wide farm field is bright green" },
      { say: "Meet your playmate.", type: "a big friendly bull waits for a fun game of tug of war" },
      { say: "Grab the rope!", type: "you pick up the thick heavy rope and hold it very tight" },
      { say: "The bull is ready.", type: "the bull grabs the other end with a wide playful grin" },
      { say: "Pull together!", type: "you both pull hard and your boots dig deep into the grass" },
      { say: "Dust puffs up.", type: "the rope stretches tight and little clouds of dust puff up" },
      { say: "It pulls back!", type: "the bull leans back and tugs you a few steps forward" },
      { say: "Stand strong.", type: "you plant your feet and pull again with all of your might" },
      { say: "It starts to slide!", type: "slowly the strong bull begins to slide across the green field" },
      { say: "One last heave!", type: "with one final mighty pull the bull crosses over the line" },
      { say: "You both win!", type: "you tumble down laughing and share a pile of fresh sweet hay" },
    ],
  },
  {
    id: "adv-dragon",
    title: "Dragon's Treasure",
    emoji: "🐲",
    bg: "img/adv-dragon-castle.jpg",
    accent: "#ff7a45",
    goalLabel: "Friendly Castle Dragon",
    intro: "A kind dragon guards a castle of gold and only wants a clever friend. Type the story to climb the castle and solve its happy riddles.",
    winText: "The dragon opens the treasure chest and shares its sparkling gems with you!",
    stages: [
      { say: "A castle in the sky.", type: "a tall castle sits on a hill glowing in the warm sunset" },
      { say: "Meet the guardian.", type: "a kind red dragon guards a room full of shiny golden coins" },
      { say: "Climb up high.", type: "you climb the steep stone steps all the way to the very top" },
      { say: "A warm welcome.", type: "the dragon greets you with a gentle and friendly smile" },
      { say: "The challenge begins.", type: "it asks you to solve three fun riddles to come inside" },
      { say: "Riddle one!", type: "the first riddle is about something that shines like the sun" },
      { say: "Think hard...", type: "you think for a moment and answer gold with a proud grin" },
      { say: "Correct!", type: "the happy dragon claps its wings and lights all the torches" },
      { say: "The door opens.", type: "the heavy treasure door creaks slowly open just for you" },
      { say: "So much sparkle!", type: "inside the gems glitter in every bright color you can imagine" },
      { say: "A treasure of friendship.", type: "the dragon shares the treasure and you become the best of friends" },
    ],
  },
  {
    id: "adv-pirate",
    title: "Treasure Island Voyage",
    emoji: "🏴‍☠️",
    bg: "img/adv-pirate-sea.jpg",
    accent: "#1fb6a8",
    goalLabel: "Hidden Pirate Treasure",
    intro: "Ahoy! A map leads to an island marked with a big red X. Type the story to sail the seas, follow the map, and dig up the buried gold.",
    winText: "X marks the spot! You lift the lid and gold coins shine in the sun!",
    stages: [
      { say: "Set sail!", type: "your wooden ship rocks gently on the deep blue rolling sea" },
      { say: "Land ahead!", type: "far away you spot a green island with tall swaying palm trees" },
      { say: "Raise the sail.", type: "you pull the ropes hard and raise the big striped sail" },
      { say: "Catch the wind.", type: "the warm wind pushes your ship faster across the bright waves" },
      { say: "A feathered friend.", type: "a red parrot flies above and squawks a cheerful hello" },
      { say: "Steer for shore.", type: "you turn the wooden wheel carefully toward the sandy beach" },
      { say: "Drop anchor.", type: "the heavy anchor splashes down and the ship comes to rest" },
      { say: "Read the map.", type: "you unroll an old map with a big red x drawn upon it" },
      { say: "Pace it out.", type: "you count ten careful steps past the tallest leaning palm tree" },
      { say: "Start digging!", type: "you dig in the warm soft sand and find a heavy old chest" },
      { say: "Treasure found!", type: "the lid pops open and bright gold coins shine in the sunlight" },
    ],
  },
  {
    id: "adv-dino",
    title: "Dino Valley Dash",
    emoji: "🦕",
    bg: "img/adv-dino-jungle.jpg",
    accent: "#46c267",
    goalLabel: "Rumbling Volcano",
    intro: "The volcano is rumbling and the dinos are scared! Type the story to lead your dino friends on a brave dash to safety across the valley.",
    winText: "Everyone reached safety! The happy dinos stomp and roar a big thank you.",
    stages: [
      { say: "A green valley.", type: "you wake up in a green valley full of friendly dinosaurs" },
      { say: "Uh oh!", type: "far away a tall volcano begins to rumble and puff out smoke" },
      { say: "Be the leader.", type: "the dinos look scared so you decide to lead them to safety" },
      { say: "Gather everyone.", type: "you wave your arms and call all the dinos to follow you" },
      { say: "Past the falls!", type: "you run together past a cool and splashing blue waterfall" },
      { say: "Cross the river.", type: "you hop from rock to rock across the sparkling river" },
      { say: "Help the little one.", type: "a tiny dino is slow so you cheer it on with a big smile" },
      { say: "Up the hill!", type: "everyone climbs a tall green hill far from the hot lava" },
      { say: "Safe at last.", type: "the volcano puffs out clouds but you are all safe now" },
      { say: "Happy stomps!", type: "the grateful dinos stomp and roar with big thankful smiles" },
      { say: "Rest and watch.", type: "you rest on the soft grass and watch the sunset all together" },
    ],
  },
  {
    id: "adv-ocean",
    title: "Ocean Rescue Dive",
    emoji: "🦈",
    bg: "img/adv-ocean-shark.jpg",
    accent: "#22b8e6",
    goalLabel: "Big Friendly Shark",
    intro: "A gentle shark has a hook stuck in its fin. Type the story to dive deep, stay calm, and carefully help your new ocean friend.",
    winText: "The shark is free and flips with joy! The whole reef cheers your bravery.",
    stages: [
      { say: "Dive in!", type: "you put on your mask and dive into the warm blue sea" },
      { say: "A colorful reef.", type: "bright colorful fish dart around the pink and orange coral" },
      { say: "Here comes a friend.", type: "a big friendly shark swims slowly and gently toward you" },
      { say: "Spot the problem.", type: "you see a tiny fish hook stuck in its soft gray fin" },
      { say: "It needs help.", type: "the shark looks at you with sad and very gentle eyes" },
      { say: "Stay calm.", type: "you float a little closer and tell the shark not to worry" },
      { say: "Hold steady.", type: "you hold the fin gently still with your careful hands" },
      { say: "Free it slowly.", type: "slowly and softly you slide the little hook right out" },
      { say: "All better!", type: "the shark wiggles happily now that the fin feels much better" },
      { say: "A joyful flip!", type: "it does a big joyful flip and spins around through the water" },
      { say: "The reef cheers!", type: "all the fish on the bright reef cheer for the brave rescue" },
    ],
  },
  {
    id: "adv-ninja",
    title: "Ninja Dojo Trials",
    emoji: "🥷",
    bg: "img/adv-ninja-dojo.jpg",
    accent: "#ef4d4d",
    goalLabel: "Master's Challenge",
    intro: "Train at the moonlit dojo to earn your typing belt. Type the story to pass each trial quietly and swiftly like a true ninja.",
    winText: "You earn the golden belt! The master bows to you with great pride.",
    stages: [
      { say: "A moonlit dojo.", type: "the dojo glows softly under the round and silver moon" },
      { say: "Petals drift down.", type: "pink cherry blossom petals float down through the night air" },
      { say: "The trials begin.", type: "the wise master asks you to pass three ninja trials" },
      { say: "Trial one: silence.", type: "first you must step across the floor without a single sound" },
      { say: "So quiet...", type: "you move so quietly that not one wooden board makes a creak" },
      { say: "Trial two: focus.", type: "next you strike the wooden training post with a quick chop" },
      { say: "Trial three: speed.", type: "then you catch three falling petals right out of the air" },
      { say: "Roll and rise!", type: "you roll across the soft mat and spring back to your feet" },
      { say: "The master nods.", type: "the master nods slowly and gives a proud little smile" },
      { say: "Earn your belt.", type: "she ties a shiny golden belt around your waist" },
      { say: "A true ninja.", type: "you bow with respect and feel as brave as a real ninja" },
    ],
  },
  {
    id: "adv-race",
    title: "Speed Racer Cup",
    emoji: "🏎️",
    bg: "img/adv-race-track.jpg",
    accent: "#ff5a4d",
    goalLabel: "Checkered Finish Line",
    intro: "Start your engines! Type the story to race your cartoon car lap after lap and cross the finish line first to win the golden cup.",
    winText: "You cross the line first! The whole crowd cheers your name out loud!",
    stages: [
      { say: "Engines roar!", type: "the engines roar loudly as the big race is about to begin" },
      { say: "At the line.", type: "your little red car shakes with excitement at the start line" },
      { say: "Green light, go!", type: "the light turns green and you zoom off in a quick flash" },
      { say: "First turn!", type: "you fly around the first sharp turn with a happy grin" },
      { say: "Catch up!", type: "a blue car is ahead but you are catching it very fast" },
      { say: "Overtake!", type: "you zip right past the blue car on the long straight track" },
      { say: "Watch out!", type: "bouncing tires roll across the road and you swerve around them" },
      { say: "The crowd roars.", type: "the cheering crowd shouts your name louder with every lap" },
      { say: "Final lap!", type: "you take the very last lap as fast as you can possibly go" },
      { say: "The finish line!", type: "you cross the finish line first under the checkered flag" },
      { say: "Champion!", type: "you lift the shiny golden cup high above your happy head" },
    ],
  },
  {
    id: "adv-robot",
    title: "Robot Factory Fix",
    emoji: "🤖",
    bg: "img/adv-robot-factory.jpg",
    accent: "#9b6bff",
    goalLabel: "Jammed Mega Robot",
    intro: "The factory robots are stuck and beeping sadly. Type the story to fix every gear and bolt and bring the cheerful robots back to life.",
    winText: "Beep boop! The robots whirr back to life and dance together with joy!",
    stages: [
      { say: "A quiet factory.", type: "the big factory is very quiet and all the robots are stuck" },
      { say: "A sad beep.", type: "the mega robot beeps sadly because its gears are all jammed" },
      { say: "Power on.", type: "you switch on the control panel and the lights blink awake" },
      { say: "Find the bolt.", type: "you find a loose bolt and tighten it with a shiny wrench" },
      { say: "Oil the gears.", type: "you add a small drop of oil to the squeaky spinning gears" },
      { say: "Belt rolling!", type: "the long conveyor belt starts to roll smoothly once again" },
      { say: "They wake up!", type: "the little robots wave their arms and beep with happy joy" },
      { say: "Fix the arm.", type: "you fix the wobbly arm so it swings gently up and down" },
      { say: "The big button.", type: "you press the big green button to wake the sleepy mega robot" },
      { say: "It dances!", type: "the mega robot blinks its eyes and does a silly happy dance" },
      { say: "A robot parade!", type: "all the robots whirr and spin together in a fun bright parade" },
    ],
  },
  {
    id: "adv-ghost",
    title: "Friendly Ghost Manor",
    emoji: "👻",
    bg: "img/adv-ghost-house.jpg",
    accent: "#7ee08a",
    goalLabel: "Shy Little Ghosts",
    intro: "The ghosts in the old manor are lonely, not scary. Type the story to share kind words and silly jokes and fill the house with giggles.",
    winText: "The ghosts glow with joy and throw a friendly party just for you!",
    stages: [
      { say: "Under the moon.", type: "an old manor stands quietly under the glowing full moon" },
      { say: "Knock knock.", type: "you knock and the creaky wooden door swings slowly open" },
      { say: "Lonely friends.", type: "inside three little ghosts float around feeling very lonely" },
      { say: "Not scary at all.", type: "they are not scary they just want a friend to play with" },
      { say: "Say hi!", type: "you smile and wave at the nearest floaty little white ghost" },
      { say: "Light the way.", type: "you light the friendly pumpkins so they glow warm and bright" },
      { say: "A happy bat.", type: "a tiny bat flaps by with big happy sparkling eyes" },
      { say: "Tell a joke!", type: "you tell a very silly joke and the ghosts start to giggle" },
      { say: "Spin and play.", type: "they spin in happy circles all around the cozy old room" },
      { say: "The manor glows.", type: "the whole manor lights up with warm and friendly cheer" },
      { say: "Party time!", type: "the ghosts throw a fun party with all of your new friends" },
    ],
  },
  {
    id: "adv-yeti",
    title: "Snowy Yeti Peak",
    emoji: "⛄",
    bg: "img/adv-yeti-peak.jpg",
    accent: "#5fb6ff",
    goalLabel: "Lonely Mountain Yeti",
    intro: "A big fluffy yeti waves from a snowy peak, hoping for a friend. Type the story to climb the cold mountain and warm its lonely heart.",
    winText: "The yeti gives you a giant fuzzy hug. Best snow day you have ever had!",
    stages: [
      { say: "Snow is falling.", type: "soft snowflakes drift down gently on a tall white mountain" },
      { say: "A friend up high.", type: "high on the peak a big fluffy yeti waves all alone" },
      { say: "Bundle up.", type: "you zip up your warm coat and pull on your cozy mittens" },
      { say: "Crunch crunch.", type: "your boots crunch through the deep and soft white snow" },
      { say: "A friendly wave.", type: "the friendly yeti waves a giant fuzzy white paw at you" },
      { say: "Build a snowman.", type: "you roll three big snowballs and stack them into a snowman" },
      { say: "It loves it!", type: "the yeti claps its huge hands with a delighted happy grin" },
      { say: "Careful climb.", type: "you climb a slippery icy ledge with slow and careful steps" },
      { say: "The very top!", type: "at last you reach the very top of the snowy mountain peak" },
      { say: "A giant hug!", type: "the happy yeti wraps you in a giant warm and fuzzy hug" },
      { say: "Play all day.", type: "you both laugh and play together in the snow all afternoon" },
    ],
  },
];
